server {
    listen 8089;
    server_name kocassets.hikvisionlatam.tech;

    access_log /var/log/nginx/kocassets_access.log;
    error_log  /var/log/nginx/kocassets_error.log;

    add_header Access-Control-Allow-Origin  * always;
    add_header Access-Control-Allow-Methods 'GET, OPTIONS' always;
    add_header Access-Control-Allow-Headers 'Content-Type, apikey, Authorization' always;

    location /ugc/ {
        alias /var/www/kocassets/ugc/;
        autoindex off;
        expires 30d;
        add_header Cache-Control 'public, immutable';
    }

    location = / {
        return 302 /ugc/;
    }

    location = /health {
        access_log off;
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}
